### ISSUE TITLE
支持非qwerty佈局

### ISSUE THREAD

**Issue by jessie-hu-95** [ywxt/rime-huma#11]
可否支持其他非qwerty鍵盤佈局？或者自定義佈局？

如果開發者沒有時間精力的話，可否給一點建議，謝謝🙏

**Comment by ywxt** [comment]
支持非qwerty佈局取決於你使用的輸入法鍵盤，本項目是一個 rime 輸入方案，只是告訴rime，怎麼把輸入的字母映射爲漢字。


另此方案專門針對 qwerty 鍵盤優化了手感，所以相比於 qwerty，使用其他佈局可能會更累手（互擊減少，跨排增多，過多使用小指等）。


---Original---
From: &quot;Jessie ***@***.***&gt;
Sent at: 2024年3月14日(Thu) AM9:48
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ywxt/rime-huma] 支持非qwerty佈局 (Issue #11)




 
可否支持其他非qwerty鍵盤佈局？或者自定義佈局？
 
如果開發者沒有時間精力的話，可否給一點建議，謝謝🙏
 
&mdash;

**Comment by jessie-hu-95** [comment]
謝謝回覆！

是的，我了解到虎碼專門為手感做了優化。我的需求是使用非qwerty的鍵盤按照虎碼在按鍵物理位置上的映射來輸入。

比如有個字的編碼是asdf，那麼我想要的效果是在非qwerty鍵盤上，依次按下左手home row上的鍵位能打出相同的字。

這個應該可以通過替換碼表中的編碼實現，但是這樣做的弊端是教學和編碼查詢就跟我個人的編碼不一樣了。有什麼方式可以更方便地做到這點嗎？

如果虎碼的文檔、網頁還有圖片是開源的我可以去做替換(^^)

**Comment by ywxt** [comment]
[虎碼官網](https://tiger-code.com/)

目前看手動替換碼表可能是比較好的解決方法。

虎碼的官網及其之上的練習和查詢工具都是不開源的，或許你可以做個瀏覽器的 extension 或者 tampermonkey 腳本來替換編碼？

除此之外，本方案也提供了 Rime 拼音反查（包括編碼和拆分），詳見README ，拆分文件爲 `huma_spelling_pseudo.dict.yaml`。

**Comment by jessie-hu-95** [comment]
好的多謝建議！

我打算先在qwerty鍵盤上練習，形成肌肉記憶後再替換碼表。

**Comment by ywxt** [comment]
虎碼網盤中有個 Windows 上的練習軟件，可以自定義碼表，配合 Rime 的反查應該就可以不用 QWERTY 鍵盤了。

~~非 Windows 嘗試 Wine 運行（小軟件應該沒有問題）~~  看起來用的是 .NET FX，或許應該用 Mono.

**Comment by ywxt** [comment]
見 跟打器 & 其他練習軟件 

字根圖的話我感覺沒有必要，從字根練起有沒有字根圖無所謂的。
