### ISSUE TITLE
編碼與官網不一致：如、强、犟

### ISSUE THREAD

**Issue by tanloong** [ywxt/rime-huma#12]
您好！發現**如**、**强**、**犟**這三個字的編碼跟官網不太一樣：

```diff
 字头：如
-编码：bd bdk
+编码：b bdk
 拆分：女口

 字头：強
-编码：bdc bdcc
+编码：bd bdcc
 拆分：弓口虫
 
 字头：强
-编码：bkc bkcq
+编码：bdc bdcq
-拆分：弓厶虫牛
+拆分：弓口虫牛
```

紅色來自 rime-huma，綠色來自虎碼的[拆分查詢](https://tiger-code.com/search?query=%E5%A6%82%E5%BC%BA%E7%8A%9F)。

**Comment by ywxt** [comment]
如和强是簡碼設置不一致，因爲我平時用的是  強 ，故沒有爲 强設置二簡。

對於 犟 則是拆分不一致，詳細參攷 #5 #8
