### ISSUE TITLE
完善三簡

### ISSUE THREAD

**Issue by orbitoo** [ywxt/rime-huma#4]
三簡存在大量空碼，可攷慮完善。
大致思路爲合幷碼表，改用lua脚本进行常用篩選。
若我有閑時我亦可做此事。
此外，建議爲一簡加入原版之快符作次選，該功䏻極實用，尤其在移動設备上。

最後，十分感謝您提供該方案，爲形碼輸入正字帶來了巨大便利！😄️

**Comment by ywxt** [comment]
感謝足下建言。

1. 三簡目前只從「常用」字集中挑字，全字集的字就我使用情況來看，非常罕用，添加三簡意義不大。如果足下指在全字集下使用諸多異體時，三簡空碼，可以攷慮增補常用字集。另外，可以詳細解釋一下 lua 做常用篩選的方法嗎？
2. 快符是指標點嗎？如果是，可以放在三選上。因爲就我而言，次選的一簡詞比較常用，單字派亦可以通過啟用單字模式使之變爲次選。

**Comment by orbitoo** [comment]
感謝回覆。

本人爲單字使用者。
余㠯爲打開全集時三簡應盡量不空，秃版之三簡在全集下存在大量生僻字，而關閉時則多爲空，不產生干擾。
關于快符，我看法與伱一致。

最後，lua寶現常用篩選，可參攷 http://huma.ysepan.com/?xzpd=1 提供之秃版方案，核心在于core2022.lua與core2022方案。

**Comment by ywxt** [comment]
我大概明白足下之意。

我可以儘量補全三選，不過由於生僻字的字頻不好統計，我也沒有太多的精力去訂正，故而最後的結果可能不太理想。

目前此方案的字集過濾實現與禿版相差不大，見 `lua/huma/charset.lua` 與 `lua/huma/charset_filter.lua`

**Comment by orbitoo** [comment]
我認爲伱可以參攷秃版中的三簡進行補足，待出現更合理字之時再修訂即可。

**Comment by ywxt** [comment]
1. 對於全集的三簡已添加，有錯誤的以後發現一個再修一個吧
2. 一簡符號已添加，需要關閉 `chinese_only` 開關 （漢字 → 外文）。
