### ISSUE TITLE
關于回頭碼的添加

### ISSUE THREAD

**Issue by orbitoo** [ywxt/rime-huma#6]
出于個人需求，我添加了 `huma.extended.dict.yaml` 文件，竝在亓中寫入了回頭碼。
當所加回頭碼原爲空碼，亓䏻正常工作；而當亓與全碼有重時，如 `yyii` 爲 `𢇏` 字之全碼，補爲 `臸` 字之回頭碼，
`臸` 則被後置。設想中應令回頭碼作前置。
經查，乃「全碼後置」功䏻所致，復查亓實現，竊㠯爲亓實現的邏輯不夠健全。

目前吾有一粗略想灋，可模仿字根之解，然不便後續調整。

**Comment by ywxt** [comment]
特碼在編碼時使用 `*` 開頭則不會後置。

如
```yaml
臸	*yyii
```

**Comment by ywxt** [comment]
或者只後置有簡碼時位於首選的詞，非首選時不後置？

**Comment by ywxt** [comment]
我在 `huma.extended.dict.yaml` 中添加了簡單的說明，可以看一下。

**Comment by orbitoo** [comment]
> 特碼在編碼時使用 `*` 開頭則不會後置。
> 
> 如
> 
> ```yaml
> 臸	*yyii
> ```

多謝，問題已解決。
